### ISSUE TITLE
Interval Queue Function lambda problems decoding and get_arg

### ISSUE THREAD

**Issue by sbaar** [aws-quickstart/connect-integration-aria#10]
I ran into a few problems with the Interval Queue Function lambda
First, it would not recognize the get_arg function and this appeared in the log. It could not see the get_arg function in act_util.py

`name 'get_arg' is not defined: NameError
Traceback (most recent call last):
File "/var/task/act_sf_interval_queue.py", line 41, in lambda_handler
sf = Salesforce(version=get_arg(os.environ, "SF_VERSION"),
NameError: name 'get_arg' is not defined`

I just copied the function to the file interval_queue.py to fix this.

Now, I am getting the following error after making a call and the recording appears in the s3 bucket.

`'utf-8' codec can't decode byte 0x90 in position 5: invalid start byte: UnicodeDecodeError
Traceback (most recent call last):
File "/var/task/act_sf_interval_queue.py", line 47, in lambda_handler
data = s3.get_object(Bucket=bucket, Key=key)["Body"].read().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 5: invalid start byte`

The exact byte 0x... varies, but I always get this error. What is proximate or root problem with this lambda function?

**Comment by KoreyPeters** [comment]
Hi sbaar.
What is the trigger that activates this lambda? It appears that you have it triggered when a CTR is produced. However, this particular function is designed to be called by a report, not a CTR.
Can you confirm that your trigger is the folder that your queue reports are being generated in to, and not the folder that your CTR records are going in to? If you have both going in to the same folder, you'll probably need to split them out.
Hopefully that makes sense.
Kind regards,
Korey
